sudo: required
matrix:
  include:
  - language: node_js
    node_js: lts/*
    cache:
      directories:
      - node_modules
    before_install:
    - npm install -g firebase-tools
    - cd code/web/
    - npm install
    script:
    - npm test
    after_success:
    - travis_wait 40 npm run build
    - firebase use default --token $FIREBASE_TOKEN
    - travis_wait firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
    on:
      branch:
      - dev
      project: kaagapai
  - language: node_js
    node_js: lts/*
    services: mysql
    cache:
      directories:
      - node_modules
    before_install:
    - cd code/api
    - npm install
    script: 'true'
    deploy:
      provider: heroku
      api_key:
        secure: AxvhJ5fKDyE+z+LxTznP6fHmhOjEMTmPPgoD6CLPto5k5q+m0xGAe2NfMz7D6LD46ccykSZPgjzQ9jJ6OxHoWigfCREsamsp+z/hNKIdpDqvNs8ineziQoXpXnvSVgV0aUek4n7nR4ttGf/TG93/2SKRm4MMEUmIRgkGeDL1wbEe8VsPtEEM3aENuGo/nSuAbkKaOCK7sRTqzP+F+HaJZKEAcwY5d/zq7E1vig/kTV3JIJxmw5Uei0g1GJML74TC/g9UK++Uiizn0wNPaw09JyRKNR6lveh+X2PPteLTFtiA0Q0jB33aWaZePhGck/bmJ6FvuSDsTv2eesx4398JYWWYmyIv0IO1wPWVtNVwX6Qq3xO9wYbB3Wa4TFbBH1cpR+i9aajFJXkkXi87JRIIFAU60S8m4gt6Jq1N7jrv3vot0PEoNqdT6gQNbFSQDKeyOKYT67UOLXN3FUd5W2j+wZjkVSpCrp5KLXdXFw8WMZjJOKXsu/qK5bX+52zTnMJ7y+10Yv9STziqPRGexXQj88gBIbvRebtCrV+ypCewONtZ1P9Ywj9cxeuv2BRwqm1g2YRERnq2Ddm7wliCf3OhfStH0NwByZOLYB515gj9B/WUXjwGLhcIWWatlXFMVtyu7v1H6icN43xNmymox8vIzGoLo9s2POy7I8YD/WFIc+M=
      app:
        dev: kaagapai-dev
      on:
        repo: JessieMTabilisma/kaagapAI-test
        branches:
          only:
          - dev

