sudo: required
matrix:
  include:
    - language: node_js
      node_js: lts/*
      cache:
        directories:
          - node_modules
      before_install:
        - npm install -g firebase-tools
        - cd code/web/
        - npm install
      script:
        - npm test
      after_success:
        - travis_wait 40 npm run build
        - firebase use default --token $FIREBASE_TOKEN
        - travis_wait firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
      on:
        branch:
          - dev
        project: kaagapai
    - language: node_js
      node_js: lts/*
      services: mysql
      cache:
        directories:
          - node_modules
      before_install:
        # - npm install -g sequelize-cli
        - cd code/api
        - npm install
      # script:
      #   - sequelize db:create
      #   - sequelize db:migrate:undo:all
      #   - sequelize db:migrate
      #   - sequelize db:seed:all
      provider: heroku
      api_key:
        secure: "$HEROKU_TOKEN"
      app: kaagapai-dev
      on:
        branch:
          - dev
