sudo: required
matrix:
  include:
  - language: node_js
    node_js: lts/*
    cache:
      directories:
      - node_modules
    before_install:
    - npm install -g firebase-tools
    - cd code/web/
    - npm install
    script:
    - npm test
    after_success:
    - travis_wait 40 npm run build
    - firebase use default --token $FIREBASE_TOKEN
    - travis_wait firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
    on:
      branch:
      - dev
      project: kaagapai
  - language: node_js
    node_js: lts/*
    services: mysql
    cache:
      directories:
      - node_modules
    before_install:
    - cd code/api
    - npm install
    script: 'true'
    deploy:
      provider: heroku
      api_key:
        secure: fhGNJew7NxWsxrSxrEoUi/KjrQSrBeQbiF26kRAqtorXNW7y8UNV86/wv4xRxcgJ3yVjUyiJZc5jjPH6pwCrKOr6imX5Fu7XDuqFLHuaS0SCNw9BsgntXeKKKsJ4Xhv7l+iheO+u75FrvaEaSrZ9sGtTFAUVcXU2f7qxmn+3fnQOe6toNbOx+ga4r/5V7CjoIcb+2b1gqXK0rYEsC6bQV5fQZd0s4a9lp80FQ6cWUePl8o2dWPMo0XKdsjhkcrH0SvpmGDTQKCe65cGloav/s93gQxdS3V/ec6H0T0dZO9yqPZDPzCfM2nT513mmonzrWsWUEhr5LX+BqlXncQL9zbV1hsRa5eIiOtdEvqVLKt38pvarDTBYUZrYr7BE3k5Cc/wqFbxPnT8utSscrwWYzp68w8xFoe5AGd/E4BlbgRccNG1Wg9P5cKri16WiWThOPPjiPe49P4USuV/6Oxy65SJPfdGJjR4hk9kU3GEVG4nMZo3lt9WtCOYCTaIgJWO1GzWkXDuNGXs4RvFIn7y+15Pp0wscaJbwKSvt71ZoKHfyXHwRoQVLDiWwvV8JS8SRxjLRp94iyRvVQT/KDksqCH2WCWId0rmJ9VtXiugZiPVheIxppWfeH5LEDcZjSDDfFm4nq+9QyJlw0ACfDXxBmJMVRt8zPr/5B9tAvllgs0s=
      app:
        dev: kaagapai-test
      on:
        repo: JessieMTabilisma/kaagapAI-test
        branches:
          only:
          - dev
