sudo: required
matrix:
  include:
    - language: node_js
      node_js: lts/*
      cache:
        directories:
          - node_modules
      before_install:
        - npm install -g firebase-tools
        - cd code/web/
        - npm install
      script:
        - npm test
      after_success:
        - travis_wait 40 npm run build
        - firebase use default --token $FIREBASE_TOKEN
        - travis_wait firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
      on:
        branch:
          - dev
        project: kaagapai
    - language: node_js
      node_js: lts/*
      services: mysql
      cache:
        directories:
          - node_modules
      before_install:
        - cd code/api
      script: "true"
      deploy:
        provider: heroku
        api_key:
          secure: GQGPi4sNBecni5CVfvAwaZdlgJrLj/nfcwT7NusfP6XGbi9xGC+4WxtG/Zh7kM1NFnrnIRmuQ4KJ7Ac1X7nR94asxNrTPpZHsyAf0DD4KA0xIJ2TdE9bI3BuKGi5018bSBSVf4vbKnqquQ0EXeC3usP4RF44IU8TWFn5y5sAR7WQNla5KwNIDslPXI/44EWK2HjifbIDjcRYXY5i028zjt9o13Rcp5hpGQzxCId+yaGLLsvxu/dgARRKbviYTd1ke/psU/Fgrf4foxaJqh3ZZPgj2oxhNgjBADUfVYij2pJW/13JvqU67KgtCoRdXfOr9/t25Xo57pDyZCv/lTLKr2bHW6dQBmd2dDvROtPhz+ptquerYrV8m0ub3+neArjuOQ8KvjJ3A1MKCup5W1y9VL0r9A5yqq8NKwGlC430/fONo18et5wFEvFDXwp5fWxH163jFRYf2VchlkS8QG8kAWodFBVzT7e1MaHT/LnGL3M/D5p9AFHi2XIfs9DwYRDKmnRl8w0yyZsgAs+XX1tsdTjR4k1AvU2WzOiJe3nLkO8UF6PaLELJl86PNe0B//Vsy3nk9hnd7E8zJZLjzLcsI9BRHcLPT/X5SLASvJAfgA8a6Iau3KwETyL/cGs66hs+d2+5K0MPWcJnbC7KBbYrqUqmnO15IbRwLqm1EGz/Zb0=
        app:
          dev: kaagapai-dev
        on:
          repo: JessieMTabilisma/kaagapAI-test
          branches:
            only:
              - dev
