# sudo: required
# services:
#   - docker

# before_install:
#   - cd code/web/
#   - docker build -t jessietabilisma/kaagapai-test -f Dockerfile.dev .

# script:
#   - docker run jessietabilisma/kaagapai-test npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "kaagapAI"
#   env: "Kaagapai-env-1"
#   bucket_name: "elasticbeanstalk-us-east-1-647912191476"
#   bucket_path: "kaagapAI"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_ACCESS_KEY"

# sudo: required
# services:
#   - docker

# before_install:
#   - cd code/web/
#   - docker build -t jessietabilisma/kaagapai .

# # script:
# #   - docker run jessietabilisma/kaagapai npm run test -- --coverage
# language: node_js
# node_js:
#   - "node"

# before_install:
#   - cd code/web/
# # script: build.sh
# cache:
#   yarn: true
#   directories:
#     - node_modules

# deploy:
#   provider: firebase
#   token:
#     secure: "$FIREBASE_TOKEN"
#   on:
#     branch: dev
#   project: "kaagapai"
# notifications:
#   email:
#     - 2164149@slu.edu.ph
#     - 2161495@slu.edu.ph
#     - 2160809@slu.edu.ph
#     - 2160120@slu.edu.ph
#     - 2161745@slu.edu.ph
#     - 2161436@slu.edu.ph
#     - 2161794@slu.edu.ph
language: node_js
node_js: lts/*
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
- cd ./functions && yarn install && cd ..
- cd ./client && yarn install && cd ..
script:
- cd ./client && yarn build && cd ..
- cd ./client && yarn test && cd ..

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: dev
  project: "kaagapai"
